# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [5]:
# Import torch
import torch
tensor_0 = torch.rand([7, 7])
tensor_0, tensor_0.shape, tensor_0.device
# Create random tensor


(tensor([[0.9768, 0.9709, 0.1258, 0.1688, 0.3315, 0.0756, 0.6617],
         [0.6780, 0.4275, 0.9751, 0.4111, 0.0301, 0.0474, 0.3020],
         [0.5317, 0.3547, 0.2851, 0.6157, 0.1511, 0.8606, 0.7691],
         [0.2924, 0.9222, 0.6503, 0.3631, 0.5752, 0.7682, 0.3204],
         [0.2763, 0.9067, 0.6853, 0.6836, 0.7671, 0.1264, 0.7975],
         [0.1959, 0.5670, 0.6929, 0.7259, 0.3529, 0.2529, 0.6002],
         [0.6284, 0.0841, 0.9417, 0.8407, 0.2947, 0.3710, 0.8276]]),
 torch.Size([7, 7]),
 device(type='cpu'))

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [12]:
# Create another random tensor

tensor_1 = torch.rand([1, 7])

print(torch.matmul(tensor_0, tensor_1.reshape([7, 1])))
print(tensor_1.reshape([7, 1]).shape)

# Perform matrix multiplication


tensor([[1.4838],
        [1.5761],
        [1.7222],
        [1.9459],
        [1.7197],
        [1.4396],
        [1.9998]])
torch.Size([7, 1])


### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [14]:
# Set manual seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
tensor_0 = torch.rand([7, 7])
torch.manual_seed(RANDOM_SEED)
tensor_1 = torch.rand([1, 7])

# Matrix multiply tensors
print(f"First tensor: {tensor_0}")
print(f"Second tensor: {tensor_1}")
print(f"Matrix Multiply is equal to: {torch.matmul(tensor_0, tensor_1.reshape([7, 1]))}")

First tensor: tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566],
        [0.7936, 0.9408, 0.1332, 0.9346, 0.5936, 0.8694, 0.5677],
        [0.7411, 0.4294, 0.8854, 0.5739, 0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317, 0.1053, 0.2695, 0.3588, 0.1994],
        [0.5472, 0.0062, 0.9516, 0.0753, 0.8860, 0.5832, 0.3376],
        [0.8090, 0.5779, 0.9040, 0.5547, 0.3423, 0.6343, 0.3644],
        [0.7104, 0.9464, 0.7890, 0.2814, 0.7886, 0.5895, 0.7539]])
Second tensor: tensor([[0.8823, 0.9150, 0.3829, 0.9593, 0.3904, 0.6009, 0.2566]])
Matrix Multiply is equal to: tensor([[3.2618],
        [3.4084],
        [2.4866],
        [1.4525],
        [1.7079],
        [2.7291],
        [2.9204]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [15]:
# Set random seed on the GPU
RANDOM_SEED = 42
torch.cuda.manual_seed(RANDOM_SEED)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [ ]:
# Set random seed
# Check for access to GPU
# Create two random tensors on GPU

#Collab Doesn't let me use GPU atm...


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [21]:
# Perform matmul on tensor_A and tensor_B
RANDOM_SEED = 1234
torch.manual_seed(RANDOM_SEED)
x = torch.rand([2, 3])
torch.manual_seed(RANDOM_SEED)
y = torch.rand([2, 3])
MM = torch.matmul(x, y.reshape([3, 2]))
print(f"MM : {MM},{MM.device}, {MM.shape} ")


MM : tensor([[0.1204, 0.3411],
        [0.0666, 0.6596]]),cpu, torch.Size([2, 2]) 


### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
print(torch.max(MM))
# Find min
print(torch.min(MM))

tensor(0.6596)
tensor(0.0666)


### 9. Find the maximum and minimum index values of the output of 7.

In [25]:
# Find arg max

print(torch.argmax(MM))
# Find arg min
print(torch.argmin(MM))

tensor(3)
tensor(2)



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [26]:
# Set seed
RANDOM_SEED = 7


# Create random tensor
torch.manual_seed(RANDOM_SEED)
tensor_0 = torch.rand([1, 1, 1, 10])

# Remove single dimensions
tensor_0_squeezed = tensor_0.squeeze()

# Print out tensors and their shapes
print(f"The first tensor: {tensor_0}, and its shape:{tensor_0.shape}")

print(f"\nThe second tensor: {tensor_0_squeezed}, and its shape:{tensor_0_squeezed.shape}")

The first tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]), and its shape:torch.Size([1, 1, 1, 10])

The second tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]), and its shape:torch.Size([10])
