## Pytorch Fundamentals

Notebook Resource : https://www.learnpytorch.io/00_pytorch_fundamentals/

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

print(torch.__version__)

2.2.1+cu121


##0:Introduction To Tensors
###Creating Tensors

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
#Amount of dimenstions inside our scalar
scalar.ndim

0

In [4]:
#Get tensor back as Python int
scalar.item()

7

In [5]:
#vector
vector = torch.tensor([7,7])
vector.ndim

1

In [6]:
vector.shape

torch.Size([2])

In [7]:
#MATRIX
MATRIX = torch.tensor([[7,8],
                      [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [8]:
MATRIX.ndim

2

In [9]:
MATRIX[1]

tensor([ 9, 10])

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
#TENSOR
TENSOR = torch.tensor([[[1,2,3],
                       [3,6,9],
                       [2,4,5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [12]:
TENSOR.ndim

3

In [13]:
TENSOR.shape

torch.Size([1, 3, 3])



---



---


###1:Random Tensors
random tensors are important because the way many neural networks learn i that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

"start with random numbers -> look  at data -> update random numbers -> look  at data -> update random numbers"

Creating Random Tensors via torch.rand(size=(n,m,...))

In [14]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape
random_image_size_tensor.ndim

3

In [15]:
random_tensor = torch.rand(size=(3,4))
random_tensor, random_tensor.ndim, random_tensor.dtype

(tensor([[0.6943, 0.3628, 0.6227, 0.9937],
         [0.8745, 0.7428, 0.4563, 0.8570],
         [0.9333, 0.0755, 0.0563, 0.2062]]),
 2,
 torch.float32)




---


---



##2:Creating a tensor with ZEROS and ONES





In [16]:
zeros = torch.zeros(size=(3,4))
zeros, zeros.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

In [17]:
ones = torch.ones(size=(3,4))
ones.ndim, ones.shape

(2, torch.Size([3, 4]))

In [18]:
##torch.arange(start, end, step)
zero_to_ten = torch.arange(start=0, end=10, step=1)
one_to_twenty = torch.arange(start=1, end=20, step=1)
print(zero_to_ten)
print(one_to_twenty)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19])


In [19]:
##Creating a tensor similar to another : torch.zeros_like(input)##
ten_zeros = torch.zeros_like(input=zero_to_ten)
twenty_ones = torch.ones_like(input= one_to_twenty)
print(ten_zeros)
print(twenty_ones)

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])




---
---
---


##3:Creating Tensors with specific Datatypes




In [20]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,#defaults to none which is torch.float32
                               device = None,#defaults to none which uses the default tensor type
                               requires_grad = False  )#if true, operations on the tensor are recorded
float_16_tensor_2 = float_32_tensor.type(torch.float16)
print(float_16_tensor_2.dtype)
float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

torch.float16


(torch.Size([3]), torch.float32, device(type='cpu'))

In [21]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = torch.float16,
                               device = "cpu")
float_16_tensor.dtype

torch.float16

In [22]:
new_tensor = float_16_tensor * float_32_tensor
new_tensor

tensor([ 9., 36., 81.])



---



---


##Three of the most common attributes about tensors:
*   shape
*   dtype
*   device

###When you encounter a problem always ask yourself: "What? what? where?..."




---



---


##Manipulating Tensors (tensor operations)
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [23]:
#Adding a number to a tensor of values
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [24]:
#multiplying by 10
tensor * 10

tensor([10, 20, 30])

In [25]:
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [26]:
torch.add(tensor, -10)

tensor([-9, -8, -7])

In [27]:
print(tensor, '*', tensor)
print('Equals = ', tensor*tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals =  tensor([1, 4, 9])




---



---


##Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. element-wise multiplication
2. matrix multiplication

there are two more rules that performing matrix multiplication needs to satisfy:
1. the **inner dimensions** must match:
* (3, 2) @ (3, 2) wont work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work

2. the resulting matrix has the shape of **outer dimentions**:
* (2, 3) @ (3, 2) => (2, 2)
* (3, 2) @ (2, 3) => (3, 3)

In [28]:
#matrix_multiplication torch.matmul(tensor_1, tensor_2)
torch.matmul(tensor, tensor)

tensor(14)

In [29]:
tensor @ tensor

tensor(14)

###one of the most common errors in deeplearning are shape error.

In [30]:
# Shapes for nnatri multiplication
tensor_A = torch.tensor([[1,2],
                         [3,4],
                         [5,6]])
tensor_B = torch.tensor([[7,10],
                         [8,11],
                         [9,12]])
#torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul

###to fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**

a **Transpose** switches the axes or dimensions of a given tensor

In [31]:

tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [32]:
print(torch.mm(tensor_A, tensor_B.T).shape)
torch.mm(tensor_A, tensor_B.T)

torch.Size([3, 3])


tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

In [33]:
torch.mm(tensor_A.T , tensor_B)

tensor([[ 76, 103],
        [100, 136]])

 ## Finding the min, max, mean, sum, etc(tensor Aggregations)

In [34]:
x = torch.arange(0,100,10)
x, x.dtype

(tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90]), torch.int64)

In [35]:
torch.min(x), x.min()

(tensor(0), tensor(0))

In [36]:
torch.max(x), x.max()

(tensor(90), tensor(90))

In [37]:
torch.mean(x.type(torch.float32)),  x.type(torch.float32).mean()
#the default dtype is "long int" but the "mean" aggregation only supports "float" or "complex" dtypes

(tensor(45.), tensor(45.))

In [38]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding The positional min and max

In [39]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [40]:
x.argmin()

tensor(0)

In [41]:
x.argmax()

tensor(9)

## Reshaping, stacking, squeesing, unsqueezzing tensors

* Reshaping  - Reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiplle tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - Removes all '1' dimensions from a tensor
Unsqueeze - adds a 'a' dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [42]:
x = torch.arange(1., 10.)
x , x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [43]:
#Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [44]:
# Changing the view
z = x.view(3,3)
z, z.shape

(tensor([[1., 2., 3.],
         [4., 5., 6.],
         [7., 8., 9.]]),
 torch.Size([3, 3]))

Changing **z** changes **x** (because a view of a tensor shares the same memory as the original input)

In [45]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3.],
         [5., 5., 6.],
         [5., 8., 9.]]),
 tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.]))

In [46]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [5., 5., 5., 5.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [5., 5., 5., 5.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [47]:
#torch.squeeze - Removes all single dimensions from a target tensor
x = torch.zeros(2,1,2,1,2)
print(x.shape)

y = torch.squeeze(x)
print(y.shape)

z = torch.squeeze(x, 0)
print(z.shape)

k = torch.squeeze(x, 1)
print(k.shape)

torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 2])
torch.Size([2, 1, 2, 1, 2])
torch.Size([2, 2, 1, 2])


In [48]:
print(f"the default tensor : {x_reshaped}")
print(f"the shape of the tensor : {x_reshaped.shape}")

the default tensor : tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
the shape of the tensor : torch.Size([1, 9])


In [49]:
print(f"the tensor after being squeezed : {x_reshaped.squeeze()}")
print(f"the size of the squeezed tensor : {x_reshaped.squeeze().shape}")
x_squeezed = x_reshaped.squeeze()

the tensor after being squeezed : tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
the size of the squeezed tensor : torch.Size([9])


###Squeeze removes Extra dimensions
###UnSqueeze = torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)

In [50]:
print(f"previous target : {x_squeezed}")
print(f"previous shape : {x_squeezed.shape}")

#Adding an extra dimension with torch.unsqueeze()
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"New Shape : {x_unsqueezed.shape}")

previous target : tensor([5., 2., 3., 5., 5., 6., 5., 8., 9.])
previous shape : torch.Size([9])

New Tensor: tensor([[5., 2., 3., 5., 5., 6., 5., 8., 9.]])
New Shape : torch.Size([1, 9])


#torch.permute - rearranges the dimensions of a target tensor in a specified order

In [51]:
x_original = torch.rand(size=(224, 224, 3)) #[height, width, colour_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) #shifts axis 0=>1, 1=>2 , 2=>0

print(f"Previous shape: {x_original.shape}")
print(f"New shape : {x_permuted.shape}") #[colour_channels, height, width]


Previous shape: torch.Size([224, 224, 3])
New shape : torch.Size([3, 224, 224])


## Indexing (selecting data from tensors with indexing)

indexing with Pytorch is similar to indexing with Numpy

In [52]:
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [53]:
#lets index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [54]:
#lets index on the middle bracket (dim=1)
x[0, 2, 1]

tensor(8)

In [55]:
#lets index on the last dimension (dim=2)
x[0, 0, 0]

tensor(1)

In [56]:
x[:, :, 1]

tensor([[2, 5, 8]])

In [57]:
x[:, 1, 1]

tensor([5])

In [58]:
x[0, 0, :]

tensor([1, 2, 3])

In [59]:
#index on x to return 9:
x[:, 2, 2]

tensor([9])

In [60]:
#index to return 3, 6, 9:
x[:, :, 2]

tensor([[3, 6, 9]])

## Pytorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in Pytorch tensor => 'torch.from_numpy(ndarrray)'
*PyTorch tensor => NumPy => 'torch.Tensor.numpy()'

In [61]:
#Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #warning when converting from numpy to pytorch, Pytorch reflects numpys default datatype of float64
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [62]:
#changing the value of the array
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [63]:
#Tensor to numpy array
tensor=torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [64]:
numpy_tensor.dtype

dtype('float32')

## Reproducbility (trying to take random out of random)

in short how a neural network learns:
start with random numbers => tensor operations => update random numbers to try and make them better representations of the data => again => again => again...

to reduce the randimness in neural networks and pytorch comes the concept of a **random seed**

essiantly what the random seed does is "flavour" the randomness.


In [65]:
import torch
#create 2 random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)



tensor([[0.6533, 0.0702, 0.3102, 0.9083],
        [0.4743, 0.6779, 0.0144, 0.5563],
        [0.7219, 0.3544, 0.3671, 0.6977]])
tensor([[0.5233, 0.4679, 0.5364, 0.5170],
        [0.8066, 0.8287, 0.7010, 0.2099],
        [0.3165, 0.1713, 0.3670, 0.9908]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [66]:
#Lets make some random but reproducible tensors

#set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED) #use everytime you create a random torch.tensor
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tesnors and pytorch objects on GPUs (and making faster computations)

GPUs = faster computation on numbers

### 1. getting a GPU
* using google collab
* use your own GPU
* use cloud computing - GCP, AWS, Azure

### 2. check for gpu access with PyTorch

In [67]:
#Checking for gpu access
import torch
torch.cuda.is_available()

False

In [69]:
#seyup device agnostic code
device = "cude" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [70]:
#count number of devices
torch.cuda.device_count()

0

## 3. putting tensors (and models) on GPU
The reason we want our tensor/model on gpu is because using a gpu resaults in faster computations

In [71]:
#create a tensor on cpu:
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [75]:
# move tensor on gpu (if Available!!)

tensor_on_gpu = tensor.to(device)
tensor_on_gpu #GPU is not available here

tensor([1, 2, 3])

### 4. Moving tensors back to CPU

In [78]:
#if tensor is on gpu, cant transform it to numpy
tensor_on_gpu.numpy() #if this was in gpu, it would give me an error


array([1, 2, 3])

In [79]:
#Lets set it to the cpu
tensor_back_on_cpu = tensor_on_gpu.cpu()

# PyTorch fudamentals Exercises & Extra-Curriculum

## Do these Exercises Before Going to the next Chapter:
Pytorch Fundamentals Exercises : https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises